# Generated by Django 5.1.5 on 2025-02-03 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StraddlePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('atm_strike', models.IntegerField()),
                ('call_price', models.FloatField()),
                ('put_price', models.FloatField()),
                ('straddle_price', models.FloatField()),
            ],
        ),
    ]
