# Generated by Django 5.1.5 on 2025-02-06 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('straddle', '0002_straddleprice_index_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='straddleprice',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Straddle Price', 'verbose_name_plural': 'Straddle Prices'},
        ),
        migrations.AlterField(
            model_name='straddleprice',
            name='atm_strike',
            field=models.PositiveIntegerField(),
        ),
    ]
