# Generated by Django 5.1.5 on 2025-02-07 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('straddle', '0004_rename_index_name_straddleprice_index_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='straddleprice',
            old_name='index_type',
            new_name='index_name',
        ),
    ]
