# Generated by Django 5.1.5 on 2025-02-10 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('straddle', '0005_rename_index_type_straddleprice_index_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='straddleprice',
            name='ltp',
            field=models.FloatField(default=0.0),
        ),
    ]
